'use client';

import { useEffect, useState } from 'react';
import Shell from '@/components/Shell';
import { supabase } from '@/lib/supabaseClient';

type Facility={id:string;name:string}; type Row=any;

export default function ShiftHandoverPage(){
 const [facilities,setFacilities]=useState<Facility[]>([]); const [rows,setRows]=useState<Row[]>([]);
 const [form,setForm]=useState({facility_id:'',shift_date:new Date().toISOString().slice(0,10),shift_type:'Gündüz',handed_by:'',received_by:'',critical_patients:'',medication_notes:'',incident_notes:'',pending_tasks:'',general_note:''});
 useEffect(()=>{load()},[]);
 async function load(){const {data:f}=await supabase.from('facilities').select('*').order('name');setFacilities(f||[]);if(f?.[0])setForm(o=>({...o,facility_id:o.facility_id||f[0].id}));const {data:r}=await supabase.from('shift_handovers').select('*').order('created_at',{ascending:false}).limit(100);setRows(r||[])}
 async function save(){const {error}=await supabase.from('shift_handovers').insert(form);if(error)return alert(error.message);setForm(o=>({...o,handed_by:'',received_by:'',critical_patients:'',medication_notes:'',incident_notes:'',pending_tasks:'',general_note:''}));await load()}
 const fname=(id:string)=>facilities.find(f=>f.id===id)?.name||'-';
 return <Shell><div className="hero"><h2>Nöbet Teslim Defteri</h2><p>Vardiya teslimi, kritik hastalar, ilaç notları ve bekleyen işler.</p></div><div className="panel"><div className="panelHead"><div><h2>Yeni Teslim</h2><p>Vardiya devrini kayıt altına al.</p></div></div><div className="grid grid4"><div><label>Kurum</label><select value={form.facility_id} onChange={e=>setForm({...form,facility_id:e.target.value})}>{facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div><label>Tarih</label><input type="date" value={form.shift_date} onChange={e=>setForm({...form,shift_date:e.target.value})}/></div><div><label>Vardiya</label><select value={form.shift_type} onChange={e=>setForm({...form,shift_type:e.target.value})}><option>Gündüz</option><option>Gece</option><option>Sabah</option><option>Akşam</option></select></div><div><label>Teslim Eden</label><input value={form.handed_by} onChange={e=>setForm({...form,handed_by:e.target.value})}/></div></div><div className="grid grid2"><div><label>Teslim Alan</label><input value={form.received_by} onChange={e=>setForm({...form,received_by:e.target.value})}/></div><div><label>Kritik Hastalar</label><textarea value={form.critical_patients} onChange={e=>setForm({...form,critical_patients:e.target.value})}/></div></div><div className="grid grid2"><div><label>İlaç Notları</label><textarea value={form.medication_notes} onChange={e=>setForm({...form,medication_notes:e.target.value})}/></div><div><label>Olay Notları</label><textarea value={form.incident_notes} onChange={e=>setForm({...form,incident_notes:e.target.value})}/></div></div><div className="grid grid2"><div><label>Bekleyen Görevler</label><textarea value={form.pending_tasks} onChange={e=>setForm({...form,pending_tasks:e.target.value})}/></div><div><label>Genel Not</label><textarea value={form.general_note} onChange={e=>setForm({...form,general_note:e.target.value})}/></div></div><div className="actions"><button className="primary" onClick={save}>Kaydet</button></div></div><div className="panel"><div className="panelHead"><div><h2>Geçmiş Teslimler</h2><p>Son 100 kayıt</p></div></div><div className="tableWrap"><table><thead><tr><th>Tarih</th><th>Kurum</th><th>Vardiya</th><th>Teslim</th><th>Kritik</th><th>İlaç</th><th>Olay</th><th>Bekleyen</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.shift_date}</td><td>{fname(r.facility_id)}</td><td>{r.shift_type}</td><td>{r.handed_by||'-'} → {r.received_by||'-'}</td><td>{r.critical_patients||'-'}</td><td>{r.medication_notes||'-'}</td><td>{r.incident_notes||'-'}</td><td>{r.pending_tasks||'-'}</td></tr>)}</tbody></table></div></div></Shell>
}
